/**
 * GeoJSON Fixture Generator
 *
 * Generates reproducible random GeoJSON data using a seeded LCG (Linear Congruential Generator).
 * Useful for unit tests, benchmarks, and integration testing.
 */

import type { Extent, GeoJsonFeature } from '../../core/index.js';

// ─── GeoJSON Types ───

export interface GeoJsonFeatureCollection {
  type: 'FeatureCollection';
  features: GeoJsonFeature[];
}

// ─── Seeded Random (LCG) ───

/**
 * Linear Congruential Generator for reproducible random numbers.
 * Uses the same constants as glibc (a=1103515245, c=12345, m=2^31).
 */
export class SeededRandom {
  private state: number;

  constructor(seed: number = 42) {
    this.state = seed >>> 0; // ensure unsigned 32-bit
  }

  /** Returns a pseudo-random number in [0, 1) */
  next(): number {
    // LCG: state = (a * state + c) mod m
    this.state = (1103515245 * this.state + 12345) & 0x7fffffff;
    return this.state / 0x80000000;
  }

  /** Returns a pseudo-random number in [min, max) */
  range(min: number, max: number): number {
    return min + this.next() * (max - min);
  }

  /** Returns a pseudo-random integer in [min, max] (inclusive) */
  rangeInt(min: number, max: number): number {
    return Math.floor(this.range(min, max + 1));
  }
}

// ─── Category Pool ───

const CATEGORIES = ['residential', 'commercial', 'industrial', 'park', 'water', 'forest', 'agriculture'];

function pickCategory(rng: SeededRandom): string {
  return CATEGORIES[rng.rangeInt(0, CATEGORIES.length - 1)]!;
}

// ─── Generators ───

/**
 * Generate random GeoJSON Point features within the given bounding box.
 */
export function generateRandomPoints(
  count: number,
  bbox: Extent,
  seed: number = 42,
): GeoJsonFeatureCollection {
  const rng = new SeededRandom(seed);
  const features: GeoJsonFeature[] = [];

  for (let i = 0; i < count; i++) {
    const lon = rng.range(bbox.minX, bbox.maxX);
    const lat = rng.range(bbox.minY, bbox.maxY);

    features.push({
      type: 'Feature',
      id: i + 1,
      geometry: {
        type: 'Point',
        coordinates: [round6(lon), round6(lat)],
      },
      properties: {
        name: `Point ${i + 1}`,
        value: round2(rng.range(0, 1000)),
        category: pickCategory(rng),
      },
    });
  }

  return { type: 'FeatureCollection', features };
}

/**
 * Generate random GeoJSON Polygon features within the given bounding box.
 * Each polygon is a convex shape generated by placing vertices around a center.
 */
export function generateRandomPolygons(
  count: number,
  bbox: Extent,
  verticesPerPolygon: number = 5,
  seed: number = 42,
): GeoJsonFeatureCollection {
  const rng = new SeededRandom(seed);
  const features: GeoJsonFeature[] = [];

  const bboxWidth = bbox.maxX - bbox.minX;
  const bboxHeight = bbox.maxY - bbox.minY;
  // Max polygon radius as fraction of bbox size
  const maxRadius = Math.min(bboxWidth, bboxHeight) * 0.05;

  for (let i = 0; i < count; i++) {
    // Center point within the bbox, inset by maxRadius so polygon stays in bounds
    const cx = rng.range(bbox.minX + maxRadius, bbox.maxX - maxRadius);
    const cy = rng.range(bbox.minY + maxRadius, bbox.maxY - maxRadius);
    const radius = rng.range(maxRadius * 0.2, maxRadius);

    // Generate angles and sort them for convex polygon
    const angles: number[] = [];
    for (let j = 0; j < verticesPerPolygon; j++) {
      angles.push(rng.range(0, 2 * Math.PI));
    }
    angles.sort((a, b) => a - b);

    const ring: number[][] = angles.map((angle) => [
      round6(cx + radius * Math.cos(angle)),
      round6(cy + radius * Math.sin(angle)),
    ]);
    // Close the ring
    ring.push([...ring[0]!]);

    features.push({
      type: 'Feature',
      id: i + 1,
      geometry: {
        type: 'Polygon',
        coordinates: [ring],
      },
      properties: {
        name: `Polygon ${i + 1}`,
        value: round2(rng.range(0, 1000)),
        category: pickCategory(rng),
      },
    });
  }

  return { type: 'FeatureCollection', features };
}

/**
 * Generate random GeoJSON LineString features within the given bounding box.
 */
export function generateRandomLineStrings(
  count: number,
  bbox: Extent,
  pointsPerLine: number = 5,
  seed: number = 42,
): GeoJsonFeatureCollection {
  const rng = new SeededRandom(seed);
  const features: GeoJsonFeature[] = [];

  for (let i = 0; i < count; i++) {
    const coords: number[][] = [];
    // Start point
    let lon = rng.range(bbox.minX, bbox.maxX);
    let lat = rng.range(bbox.minY, bbox.maxY);

    const stepX = (bbox.maxX - bbox.minX) * 0.05;
    const stepY = (bbox.maxY - bbox.minY) * 0.05;

    for (let j = 0; j < pointsPerLine; j++) {
      coords.push([round6(lon), round6(lat)]);
      // Random walk for next point
      lon = Math.max(bbox.minX, Math.min(bbox.maxX, lon + rng.range(-stepX, stepX)));
      lat = Math.max(bbox.minY, Math.min(bbox.maxY, lat + rng.range(-stepY, stepY)));
    }

    features.push({
      type: 'Feature',
      id: i + 1,
      geometry: {
        type: 'LineString',
        coordinates: coords,
      },
      properties: {
        name: `Line ${i + 1}`,
        value: round2(rng.range(0, 1000)),
        category: pickCategory(rng),
      },
    });
  }

  return { type: 'FeatureCollection', features };
}

// ─── Helpers ───

function round6(n: number): number {
  return Math.round(n * 1_000_000) / 1_000_000;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
